on:
  push:
    branches:
      - trunk

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: make publish

      - uses: peaceiris/actions-gh-pages@v3
        with:
          exclude_assets: ".github,.gitignore,.npmrc,netlify.toml,node_modules,package.json,readme.md"
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: www
          publish_dir: ./